module Main3
  UNUSED_VAR = 123

  def useless2(method)
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
    puts "bullshit"
  end

  def useless(method)
    puts "bullshit"
  end
end

